apiVersion: v1
kind: ConfigMap
metadata:
  name: librespeed-env
  namespace: final
data:
  MODE: "frontend"
  TELEMETRY: "true"
  ENABLE_ID_OBFUSCATION: "true"
  REDACT_IP_ADDR: "true"
  IP_ADDRESS_OPTION: "0"

  DB_TYPE: "mysql"
  DB_HOSTNAME: "mysql.db.svc.cluster.local"
  DB_NAME: "librespeed"
  DB_USERNAME: "librespeed"
