apiVersion: v1
kind: Secret
metadata:
  name: registrysecret
  namespace: final
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5yZWJyYWlubWUuY29tIjp7InVzZXJuYW1lIjoicHVsbC1jcmVkcyIsInBhc3N3b3JkIjoiZ2xkdC1IdEdfSkhCTVh5ekNDaUpBZ3B6aCIsImF1dGgiOiJjSFZzYkMxamNtVmtjenBuYkdSMExVaDBSMTlLU0VKTldIbDZRME5wU2tGbmNIcG8ifX19
